---
- name: Provision Control Planes
  xenserver_guest:
    hostname: "{{ xen_server_ip }}"
    username: "{{ xen_username }}"
    password: "{{ xen_password }}"
    validate_certs: no
    name: "control_{{ item }}"
    state: poweredon
    template_uuid: "{{ xen_template }}"
    disks:
      - size_gb: "{{ control_disk_size }}"
        sr: "Local storage"
    hardware:
      memory_mb: "{{ control_memory }}"
      num_cpus: "{{ control_cpu }}"
    networks:
      - name: "{{ xen_network_name }}"
        type: dhcp
    wait_for_ip_address: yes
  with_sequence: start=1 end="{{ num_control }}"
  register: control_vms

- name: Add to Inventory
  add_host:
    name: "{{ item.instance.networks[0].ip }}"
    groups: control_nodes
  with_items: "{{ control_vms.results }}"
