---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: "kube-state-metrics"
        static_configs:
          - targets:
              - "kube-state-metrics.kube-system.svc.cluster.local:8080"
              - "kube-state-metrics.kube-system.svc:8080"
              - "kube-state-metrics.kube-system.svc:8081"
      - job_name: "kubelet_https"
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
      - job_name: "kubelet_http"
        kubernetes_sd_configs:
          - role: node
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true