---
- name: Provition etcds
  xenserver_guest:
    hostname: "{{ xen_server_ip }}"
    username: "{{ xen_username }}"
    password: "{{ xen_password }}"
    validate_certs: no
    name: "{{ item }}"
    state: poweredon
    template: "{{ xen_template }}"
    disks:
      - size_gb: "{{ etcd_disk_size }}"
        sr: "Local storage"
    hardware:
      memory_mb: "{{ etcd_memory }}"
      num_cpus: "{{ etcd_cpu }}"
    networks:
      - name: "{{ xen_network_name }}"
        type: dhcp
    wait_for_ip_address: yes
  loop: "{{ query('sequence', start=0, end=num_etcd)}}"
  # loop:
  #   - etcd_01
  #   - etcd_02
  register: etcd_vms

- name: Add to Inventory
  add_host:
    name: "{{ item.instance.networks[0].ip }}"
    groups: etcd_nodes
  with_items: "{{ etcd_vms.results }}"