---
- name: Provision etcds
  xenserver_guest:
    hostname: "{{ xen_server_ip }}"
    username: "{{ xen_username }}"
    password: "{{ xen_password }}"
    validate_certs: no
    name: "etcd_{{ item }}"
    state: poweredon
    template_uuid: "{{ xen_template }}"
    disks:
      - size_gb: "{{ etcd_disk_size }}"
        sr: "Local storage"
    hardware:
      memory_mb: "{{ etcd_memory }}"
      num_cpus: "{{ etcd_cpu }}"
    networks:
      - name: "{{ xen_network_name }}"
        type: dhcp
    wait_for_ip_address: yes
  with_sequence: start=1 end="{{num_etcd }}"
  register: etcd_vms

- name: Add to Inventory
  add_host:
    name: "{{ item.instance.networks[0].ip }}"
    groups: etcd_nodes
  with_items: "{{ etcd_vms.results }}"