---
- name: Set VCPU Priority
  command: xe vm-param-set VCPUs-params:weight="{{ cpu_weight }}" uuid="{{ vm_uuid.stdout }}"

- name: Set VCPU Count Max
  command: xe vm-param-set VCPUs-max="{{ vcpu_count }}" uuid="{{ vm_uuid.stdout }}"

- name: Set VCPU Count at Startup
  command: xe vm-param-set VCPUs-at-startup="{{ vcpu_count }}" uuid="{{ vm_uuid.stdout }}"

- name: Get UUID of VM Disk
  command: xe vm-disk-list vbd-params=device=xvda uuid="{{ vm_uuid.stdout }}" --minimal
  register: vdi_uuid

- name: Set Disk Size
  command: xe vdi-resize disk-size="{{ disk_size }}" uuid="{{ vdi_uuid.stdout }}"

- name: Set Memory
  command: xe vm-memory-limits-set dynamic-min="{{ memory }}" dynamic-max="{{ memory }}" static-max="{{ memory }}" static-min="{{ memory }}" uuid="{{ vm_uuid.stdout }}"

- name: Get Network UUID
  command: xe network-list name-label="{{ network_name }}" --minimal
  register: network_uuid

- name: Attach VM to Network
  command: xe vif-create network-uuid="{{ network_uuid.stdout }}" mac=random device=0 vm-uuid="{{ vm_uuid.stdout }}"

- name: Create and Attach CD-ROM Drive
  command: xe vbd-create type=CD device=xvdd vm-uuid="{{ vm_uuid.stdout }}" mode=ro
