---
- name: Install Required Packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - haproxy

- name: Test template
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Restart haproxy
  service:
    name: haproxy
    state: restarted