---
- name: Disable swap
  command: swapoff -a

- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - kubeadm
    - kubectl

- name: Start Services
  service:
    name: "{{ item }}"
    state: started
  loop:
    - docker
    - kubelet
    - firewalld
