---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-ci
spec:
  selector:
    app: hello-world
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-np
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30046