---
- name: Configure Master Nodes
  hosts: etcd_nodes, control_nodes
  vars:
    ip_addr: 10.0.3.19
  tasks:
    - name: Pull images required for cluster
      command: kubeadm config images pull

    - name: Initialize cluster
      command: kubeadm init --apiserver-advertise-address "{{ ip_addr }}"
      register: kubeadm_output
      ignore_errors: yes

    - name: Store logs and token
      become: false
      local_action: copy content="{{ kubeadm_output.stdout }}" dest="./logs.json"

    - name: Get kubeconfig file
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: kube-inventory.conf
