---
- name: Configure Nodes
  hosts: etcd_nodes, control_nodes
  tasks:
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a

    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - vim
        - bash
        - curl
        - apt-transport-https
        - gnupg2
        - firewalld

    - name: Add keys
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add K8s APT Repo
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install K8s Packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - kubeadm
        - kubelet
        - kubectl
        - docker-engine

    - name: Start Services
      service:
        name: "{{ item }}"
        state: started
      loop:
        - docker
        - kubelet
        - firewalld
