---
- name: Install Dependency Packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ kubernetes_required_packages }}"

- name: Uninstall Old Versions of Docker
  package:
    name: "{{ item }}"
    state: absent
  loop: "{{ old_docker_packages }}"

- name: Add Docker GPG Key
  apt_key:
    url: "{{ docker_gpg_key }}"
    state: present

- name: Add Docker APT Repo
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: Add Kubernetes GPG APT keys
  apt_key:
    url: "{{ kubernetes_apt_key }}"
    state: present

- name: Add Kubernetes APT Repo
  apt_repository:
    repo: "{{ kubernetes_apt_repo }}"
    state: present

- name: Install required packages for masters
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ kubernetes_packages_master }}"
  when: "'master' in kubernetes_roles"

- name: Install required packages for workers
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ kubernetes_packages_master }}"
  when: "'worker' in kubernetes_roles"

- name: Start services
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ kubernetes_nodes_services }}"

- name: Remove Swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable Swap
  command: swapoff -a
