---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: app.test.com
      http:
        paths:
          - path: /spring
            backend:
              serviceName: spring-app-ci
              servicePort: 80
          - path: /hello-world
            backend:
              serviceName: hello-world-ci
              servicePort: 80
    - host: local.minikube.com
      http:
        paths:
          - path: /spring
            backend:
              serviceName: spring-app-ci
              servicePort: 80
          - path: /hello-world
            backend:
              serviceName: hello-world-ci
              servicePort: 80
