---
- name: Check if kubernetes has been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Install Kubeadm Packages
  command: kubeadm config images pull
  when: not kubernetes_init_stat.stat.exists

- name: Create cluster with control plane endpoint
  block:
    - name: Init master
      command: >
        kubeadm init
        --control-plane-endpoint "{{ hostvars[groups.loadbalancers[0]].ansible_host }}:6443"
        --upload-certs
        --pod-network-cidr="{{ kubernetes_network.pod_network_cidr }}"
        --ignore-preflight-errors="{{ kubernetes_ignore_preflight_erros }}"
      register: kubeadm_output
      when:
    - name: Print kubeadm output
      debug:
        var: kubeadm_output
  when:
    - master_creation_mode == "control_plane"
    - not kubernetes_init_stat.stat.exists

- name: Create cluster with advertise apiserver address
  block:
    - name: Init master
      command: >
        kubeadm init
        --apiserver-advertise-address={{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}
        --upload-certs
        --pod-network-cidr="{{ kubernetes_network.pod_network_cidr }}"
        --ignore-preflight-errors="{{ kubernetes_ignore_preflight_erros }}"
      register: kubeadm_output
    - name: Print kubeadm init output
      debug:
        var: kubeadm_output
  when:
    - master_creation_mode == "advertise_ip"
    - not kubernetes_init_stat.stat.exists

- name: Get kubeconfig file
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ../kubeconfigs
  when: "'controlplane' in kubernetes_roles"

- name: Ensure .kube directory exists
  file:
    path: ~/.kube
    state: directory

- name: Symlink kubeconfig to ~/.kube/config
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

- name: Taint master
  command: "{{ kubernetes_taint_command }}"
  when: kubernetes_taint_master == true

- name: Configure flannel cni plugin
  command: "{{ item }}"
  with_items:
    - kubectl apply -f {{ kubernetes_flannel_manifest_file_rbac }}
    - kubectl apply -f {{ kubernetes_flannel_manifest_file }}
  register: flannel_result
  changed_when: "'created' in flannel_result.stdout"
  when: kubernetes_network.cni == "flannel"
  tags:
    - kubernetes_cni

- name: Configure weave cni plugin
  block:
    - name: Get kubernetes version for weave installation.
      shell: kubectl version | base64 | tr -d '\n'
      changed_when: false
      register: kubectl_version
    - name: Install weave network plugin
      command: "kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version={{ kubectl_version.stdout_lines[0] }}"
      register: weave_result
      changed_when:
        - "'created' in weave_result.stdout"
        - "'configured' in weave_result.stdout"
  when: kubernetes_network.cni == "weave"
  tags:
    - kubernetes_cni

- name: Add ingress nginx controller
  command: kubectl apply -f "{{ kubernetes_ingress_controller }}"
  register: nginx_ingress_result
  changed_when:
    - "'created' in nginx_ingress_result.stdout"

- name: Check if dashboard ui service exists
  shell: kubectl get services --namespace kube-system | grep -q kubernetes-dashboard
  changed_when: false
  failed_when: false
  register: has_kubernetes_dashboard_service
  when: kubernetes_enable_dashboard | bool
  tags:
    - kubernetes_dashboard

- name: Enable dashboard ui
  command: kubectl apply -f "{{ kubernetes_dashboard_manifest }}"
  when: kubernetes_enable_dashboard | bool
  register: dashboard_result
  changed_when:
    - "'created' in dashboard_result.stdout"
    - "'configured' in dashboard_result.stdout"
  tags:
    - kubernetes_dashboard
