---
- name: Configure SSH Keys
  hosts: k8s_nodes
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_pass: 123123
  tasks:
    - name: Distribute Keys
      authorized_key:
        user: monitoring
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Disable root password login
      replace:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin yes"
        replace: "PermitRootLogin prohibit-password"
