---
- name: Create initial master node
  hosts: control_nodes
  roles:
    - lucastercas.initialize_master

- name: Configure worker nodes
  hosts: kubernetes_nodes
  roles:
    - lucastercas.create_worker
