---
all:
  hosts:
    xen_01:
      ansible_host: 10.0.3.81
    loadbalancer_01:
      ansible_host: 167.71.97.142
    master_01:
      ansible_host: 104.131.45.230
    worker_01:
      ansible_host: 167.71.97.100

  children:
    kubernetes_nodes:
      children:
        etcd_nodes:
        control_nodes:
          hosts:
            master_01:
        worker_nodes:
          hosts:
            worker_01:
    loadbalancers:
      hosts:
        loadbalancer_01:
    xen_servers:
      hosts:
        xen_01:
