---
all:
  hosts:
    # xen_01:
    # ansible_host: 10.0.3.81
    loadbalancer_01:
      ansible_host: 104.131.42.145
    master_01:
      ansible_host: 104.131.41.105
    worker_01:
      ansible_host: 209.97.151.247
    worker_02:
      ansible_host: 104.131.42.13

  children:
    kubernetes_nodes:
      children:
        etcd_nodes:
        control_nodes:
          hosts:
            master_01:
        worker_nodes:
          hosts:
            worker_01:
            worker_02:
    loadbalancers:
      hosts:
        loadbalancer_01:
    xen_servers:
      hosts:
        xen_01:
