---
all:
  hosts:
    xen_01:
      ansible_host: 10.0.3.81
    loadbalancer_01:
      ansible_host: 167.71.106.134
    master_01:
      ansible_host: 104.131.31.215
    worker_01:
      ansible_host: 167.71.98.153
    worker_02:
      ansible_host: 104.131.44.138

  children:
    kubernetes_nodes:
      children:
        etcd_nodes:
        control_nodes:
          hosts:
            master_01:
        worker_nodes:
          hosts:
            worker_01:
            worker_02:
    loadbalancers:
      hosts:
        loadbalancer_01:
    xen_servers:
      hosts:
        xen_01:
