---
all:
  hosts:
    xen_01:
      ansible_host: 10.0.3.81
    loadbalancer_01:
      ansible_host: 104.131.35.85
    master_01:
      ansible_host: 167.71.163.95

  children:
    k8s_nodes:
      children:
        etcd_nodes:
        control_nodes:
          hosts:
            master_01:
        worker_nodes:
    loadbalancers:
      hosts:
        loadbalancer_01:
    xen_servers:
      hosts:
        xen_01:
