---
all:
  hosts:
    # xen_01:
    # ansible_host: 10.0.3.81
    loadbalancer_01:
      ansible_host: 142.93.74.24
    master_01:
      ansible_host: 104.131.2.80
    worker_01:
      ansible_host: 104.131.42.193
    worker_02:
      ansible_host: 104.131.27.33

  children:
    kubernetes_nodes:
      children:
        etcd_nodes:
        control_nodes:
          hosts:
            master_01:
        worker_nodes:
          hosts:
            worker_01:
            worker_02:
    loadbalancers:
      hosts:
        loadbalancer_01:
    xen_servers:
      hosts:
        xen_01:
