---
all:
  hosts:
    xen_01:
      ansible_host: 10.0.3.81
    loadbalancer_01:
      ansible_host: 157.245.9.118
    master_01:
      ansible_host: 104.131.30.15
    worker_01:
      ansible_host: 104.131.47.146
    # worker_02:
    #   ansible_host: 104.131.47.49

  children:
    kubernetes_nodes:
      children:
        etcd_nodes:
        control_nodes:
          hosts:
            master_01:
        worker_nodes:
          hosts:
            worker_01:
          #   worker_02:
    loadbalancers:
      hosts:
        loadbalancer_01:
    xen_servers:
      hosts:
        xen_01:
