---
all:
  hosts:
    # xen_01:
      # ansible_host: 10.0.3.81
    # loadbalancer_01:
      # ansible_host: 157.245.120.185
    master_01:
      ansible_host: 167.71.99.253
    worker_01:
      ansible_host: 167.71.242.114
    worker_02:
      ansible_host: 68.183.60.166

  children:
    kubernetes_nodes:
      children:
        etcd_nodes:
        control_nodes:
          hosts:
            master_01:
        worker_nodes:
          hosts:
            worker_01:
            worker_02:
    loadbalancers:
      # hosts:
        # loadbalancer_01:
    xen_servers:
      hosts:
        xen_01:
