---
all:
  hosts:
    xen_01:
      ansible_host: 10.0.3.81

  children:
    k8s_nodes:
      children:
        etcd_nodes:
        control_nodes:
        worker_nodes:
        loadbalancer:
    xen_servers:
      hosts:
        xen_01:
