---
all:
  hosts:
    xen_01:
      ansible_host: 10.0.3.81
    loadbalancer_01:
      ansible_host: 104.131.40.47
    master_01:
      ansible_host: 104.131.34.174
    worker_01:
      ansible_host: 104.131.35.100

  children:
    k8s_nodes:
      children:
        etcd_nodes:
        control_nodes:
          hosts:
            master_01:
        worker_nodes:
          hosts:
            worker_01:
    loadbalancers:
      hosts:
        loadbalancer_01:
    xen_servers:
      hosts:
        xen_01:
