---
- name: Provisioning VMs
  hosts: xen_servers
  tasks:
    - name: Create ETCD Nodes
      xenserver_guest:
        hostname: 10.0.3.81
        username: root
        password: Mateus@2020
        validate_certs: no
        name: etcd_01
        state: poweredon
        template: "Test k8s 1.0 - Debian 9"
        disks:
          - size_gb: "30"
            sr: "Local storage"
        hardware:
          memory_mb: 2048
          num_cpus: 2
        networks:
          - name: "Network 0"
            type: static
            ip: 10.0.3.143
        wait_for_ip_address: yes
      register: etcd_01

    - name: Create Control Plane Nodes
      xenserver_guest:
        hostname: 10.0.3.81
        username: root
        password: Mateus@2020
        validate_certs: no
        name: control_01
        state: poweredon
        template: "Test k8s 1.0 - Debian 9"
        disks:
          - size_gb: "30"
            sr: "Local storage"
        hardware:
          memory_mb: 2048
          num_cpus: 2
        networks:
          - name: "Network 0"
            type: static
            ip: 10.0.3.150
        wait_for_ip_address: yes
      register: control_01

    - name: Add ETCDs to Inventory
      add_host:
        name: "{{ etcd_01.instance.networks[0].ip }}"
        groups: etcd

    - name: Add Control Plane to Inventory
      add_host:
        name: "{{ control_01.instanc.networks[0].ip }}"
        groups: control_plane
    
    - name: IPs of ETCD
      connection: local
      debug: 
        msg: IP {{ etcd_01.instance.networks[0].ip }}

    - name: IPs of Control Plane
      connection: local
      debug: 
        msg: IP {{ control_01.instance.networks[0].ip }}