---
- name: Provisioning VMs
  hosts: xen_servers
  tasks:
    - name: Create ETCD Nodes
      xenserver_guest:
        hostname: 10.0.3.81
        username: root
        password: Mateus@2020
        validate_certs: no
        name: etcd_01
        state: present
        template: "Test Debian Stretch 9.0"
        disks:
          - size_gb: 30
            sr: "Local storage"
        hardware:
          memory_mb: 2048
          num_cpus: 2
        networks:
          - name: "Pool-wide network associated with eth0"
        wait_for_ip_address: yes
        cdrom:
          type: iso
          iso_name: guest-tools.iso
      delegate_to: 10.0.3.81
      register: etcd_01_uuid

    - name: Create Control Plane Nodes
      xenserver_guest:
        hostname: 10.0.3.81
        username: root
        password: Mateus@2020
        validate_certs: no
        name: control_01
        state: present
        template: "Test Debian Stretch 9.0"
        disks:
          - size_gb: 30
            sr: "Local storage"
        hardware:
          memory_mb: 2048
          num_cpus: 2
        networks:
          - name: "Pool-wide network associated with eth0"
        wait_for_ip_address: yes
        cdrom:
          type: iso
          iso_name: guest-tools.iso
      delegate_to: 10.0.3.81
      register: control_01_uuid
