---
# - import_playbook: provision_nodes.yml
# - import_playbook: configure_access.yml
- import_playbook: configure_kubernetes_nodes.yml
- import_playbook: configure_loadbalancers.yml
- import_playbook: create_cluster.yml
