---
- name: Install Dependency Packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - curl
    - apt-transport-https
    - gnupg2
    - firewalld
    - ca-certificates
    - gnupg-agent
    - software-properties-common

- name: Uninstall Old Versions of Docker
  package:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Add Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker APT Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present

- name: Add Kubernetes GPG APT keys
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes APT Repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install required packages for masters
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - kubeadm
    - kubelet
    - kubectl
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: "'master' in kubernetes_role"

- name: Install required packages for workers
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - kubeadm
    - kubelet
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: "'worker' in kubernetes_role"

- name: Start services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - docker
    - kubelet
    - firewalld
    - sshd

- name: Remove Swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable Swap
  command: swapoff -a
